---

- name: Ensure hosts file is correct
  lineinfile:
    path: /etc/hosts
    regexp: "{{jenkins_url_external}}"
    line: "{{ ansible_eth0.ipv4.address }} {{jenkins_url_external}}"
    owner: root
    group: root
    mode: 064
  when: "{{jenkins_url_external}} != ''"

# Install all OS packages (including Jenkins itself).
- include: "packages_{{ ansible_os_family }}.yml"

# Configure the service's launch options.
- include: "service_config_{{ ansible_os_family }}.yml"

- name: Create Jenkins Init Script Directory
  # Reference: https://wiki.jenkins-ci.org/display/JENKINS/Post-initialization+script
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755
  become: true

- name: Jenkins Script - Configure Settings
  template:
    src: configureSettings.groovy
    dest: /var/lib/jenkins/init.groovy.d/configureSettings.groovy
    owner: jenkins
    group: jenkins
    mode: 0744
  become: true
  notify:
    - "Restart Service 'jenkins'"

# Enable the Jenkins CLI.
- include: "cli_config.yml"

# Install and/or update plugins.
- include: "plugins.yml"

- name: Ensure Service 'jenkins' Is Running
  service:
    name: jenkins
    state: started
    enabled: yes
  become: true

- name: Grab Jenkins Web UI Content
  # By default, Jenkins 2 is set to require auth, so the only page we can grab
  # without getting a 403 and redirect is the login page.
  uri:
    url: "http://localhost:{{ jenkins_port }}{{ jenkins_context_path | default('') }}/login"
    return_content: true
  register: jenkins_ui

- name: Verify Jenkins Web UI Content
  action: fail
  when: jenkins_ui.content.find('Jenkins ver. 2') == -1
