---
# This file is not included by default. It can be included via a task:
# include: "packages_{{ ansible_os_family }}.yml"

- name: download the YUM repo for Jenkins2
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    checksum: "{{jenkins_yum_repo_checksum}}"

- name: download the repo gpg key
  get_url:
    url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    dest: /var/tmp/.jenkins.key
    checksum: "{{jenkins_yum_key_checksum}}"

- name: import the jenkins key
  rpm_key:
    state: present
    key: /var/tmp/.jenkins.key

- name: install the Jenkins fonts
  yum: pkg={{item}} state=installed
  with_items: 
   - dejavu-sans-fonts
   - fontconfig

- name: install the Jenkins package
  yum:
    name: "jenkins-{{jenkins_version}}"
    state: present
