---
# This file is not included by default. It can be included via a task:
# include: "packages_{{ ansible_os_family }}.yml"

- name: download the YUM repo for Jenkins2
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    checksum: 1b0402adddacc6d8b58395572eff03fa

- name: download the repo gpg key
  get_url:
    url: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    dest: /var/tmp/.jenkins.key
    checksum: 9500ca61a5a755c2d3d5815e94142f6d

- name: import the jenkins key
  rpm_key:
    state: present
    key: /var/tmp/.jenkins.key
